spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:dash

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

jwt:
  secret-key: 1234
  access-token-valid-time: 1800000 # 30분
  refresh-token-valid-time: 1209600000 # 2주

kakao:
  client-id: 1234
